# DATA_DIR = "/content/drive/MyDrive/data/"
# CHECKPOINT_PATH = "/content/drive/MyDrive/data/MNIST/checkpoint"
# PLOT_PATH = "/content/drive/MyDrive/data/MNIST/plots"
# NUM_WORKERS = 1
# DEVICE = "cuda"
# BATCH_SIZE = 32
# EPOCHS = 10
# RANDOM_SEED = 42

DATA_DIR = "../data/FirstTrainingData"
JSON_FILE = "../data/FirstTrainingData/GroundTruth.json"
CHECKPOINT_PATH = "../checkpoint"
PLOT_PATH = "../plots"
BATCH_SIZE = 8
IMAGE_WIDTH = 300
IMAGE_HEIGHT = 75
NUM_WORKERS = 0
DEVICE = "cpu"
EPOCHS = 2
lr = 0.001
RANDOM_SEED = 42
FEATURES = ['FreshWeightShoot', 'DryWeightShoot', 'Height', 'Diameter', 'LeafArea']